version: '3.4'

services:
  erp.product.api:
    container_name: erp-product-container
    image: ${DOCKER_REGISTRY-}erpproduct
    build:
      context: .
      dockerfile: src/ERP.Product.API/Dockerfile

  postgres:
    container_name: postgres-container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: erpproductdb
    ports:
      - "5432:5432"